### ISSUE TITLE
Compile Error: File to import not found or unreadable: css/vendor/normalize.min. on Ubuntu

### ISSUE THREAD

**Issue by KhadijaMahanga** [CodeForAfrica/HURUmap-apps#71] opened 2018-05-29 06:57 UTC
## Description
I am having a compile error on Ubuntu  while running HURUmap-apps `python manage.py runserver`:
```
CompileError at /
Error: File to import not found or unreadable: css/vendor/normalize.min.
        on line 1 of env/lib/python2.7/site-packages/wazimap/static/css/_censusreporter.scss
        from line 7 of env/lib/python2.7/site-packages/wazimap/static/css/wazimap.scss
>> @import "css/vendor/normalize.min";
```

## To Reproduce
Clone `HURUmap-apps`, set up virtual environment, and run pip install requirements. Set up databases and start server

**Comment by DavidLemayian** [comment] 2018-05-29 13:42
@KhadijaMahanga Yip. This is a duplicate of #66 . cc @phillipahereza

**Closed as completed by DavidLemayian** 2018-05-29 13:42 UTC
Labels: bug
